# Generated by Django 6.0.7 on 2026-08-11 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hicam_app', '0002_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
